"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/srdFSq71XFW
 */

import FormCard from "~/components/component/form-card";
import ResultCard from "~/components/component/result-card";
import useGenerator from "~/hooks/use-generator";

export default function Generator() {
  const {
    inputs,
    isGenerating,
    generatedResponse,
    handleInputChange,
    handleSubmit,
  } = useGenerator();

  return (
    <main
      key="1"
      className="flex flex-col items-center justify-center min-h-screen py-2"
    >
      <FormCard
        {...inputs}
        isGenerating={isGenerating}
        handleInputChange={handleInputChange}
        handleSubmit={handleSubmit}
      />
      <ResultCard generatedResponse={generatedResponse} />
    </main>
  );
}
